### ISSUE TITLE
How to set constraint on input and output token

### ISSUE THREAD

**Issue by climber2002** [bcc-research/CFMMRouter.jl#20]
Hello, firstly thanks a lot for this interesting project. I have an arbitrage bot, like what Theo introduced in the youtube video, I model this as a graph problem. For my bot I model tokens as vertices and pools as edges. And when try arbitrage I will start from one node (base token, e.g. WETH) and then do DFS search to find the output to be also base token and then calculate if there is a profit.

I have a question about how to restrict input and output to only one token (e.g. I want both input and output token to be only base token) when run arbitrage, just like what I did using graph solution. Sorry if this is a dumb question since I'm still new to Convex Optimisation. Thanks again.

**Comment by tjdiamandis** [comment]
Check out the Objectives section of the docs

**Comment by climber2002** [comment]
Thanks @tjdiamandis for your answer, I've reread the docs and also rewatched your youtube video. In the Objectives section it only talked about [LinearNonnegative](https://bcc-research.github.io/CFMMRouter.jl/dev/objective/#LinearNonnegative-(arbitrage)). I reckon here we need to specify some constraints? And also in your video (at about 7min) you mentioned that I could set weth price to 1 and price of other tokens to 0 if I only want weth out. I tried to set `prices = [1.0, 0]` in the arbitrage example, however it gave following error,

```
ERROR: ArgumentError: all elements must be strictly positive
Stacktrace:
 [1] LinearNonnegative(c::Vector{Float64})
   @ CFMMRouter ~/.julia/packages/CFMMRouter/iqAFS/src/objectives.jl:54
 [2] top-level scope
   @ REPL[7]:1
``` 

It seems for `LinearNonnegative` it requires all prices to be strictly positive. 

Any hint is really appreciated 🙏 , and thanks again for providing this project.
